# baseURL
@baseURL = http://localhost:4000

###
# Find All Orders
GET {{ baseURL }}/orders

###
# Create Order
POST {{ baseURL }}/orders
Content-Type: application/json

{   
    "product_id": "944a3a34-769d-453d-a88d-21f7477a13c7",
    "customer_id": "9abb739b-a70f-4567-9340-94863d1a2d79",
    "unit": 1,
    "price": 100000,
    "discount": 5000
}

